services:
  - type: web
    name: smart-expense-tracker-api
    env: docker
    plan: free # Note: The free plan may sleep after inactivity.
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      # Pulls the internal connection string from your Render PostgreSQL service
      - key: DATABASE_URL
        fromDatabase:
          name: expense-tracker-db # <--- IMPORTANT: Change this!
          property: connectionString
      # Set your JWT secret directly
      - key: jwt.secret
        value: A5hC0JKUPviOAQAHoks1gRmuZVnR4kz1dF4VYszDbUE4PDOiyJBNA67a7mlrcxS2 # <--- IMPORTANT: Change this!